config/routes.rb
FeedbackIt::Application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :feedbacks do 
    resources :votes
    resources :downvotes
  end

  get "static_pages/index"
  get "profile" => "users#index"
  get "sort" => "static_pages#sort"
  match "reply/:feedback_id" => "feedbacks#reply", as: 'reply', via: :get
  post "reply_to_user" => "feedbacks#reply_to_user"

  root 'static_pages#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :feedbacks
	has_one :admin
end

app/models/downvote.rb
class Downvote < ActiveRecord::Base
  belongs_to :user
  belongs_to :feedback
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :category
  belongs_to :tag
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :downvotes, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :heading, presence: true, length: { maximum: 100 }
  validates :feedback_content, presence: true, length: { minimum: 20 }
  validates_date :when, presence: true, on_or_before: :today
  validates :where, presence: true, length: { maximum: 100 }
  validates :category, presence: true
  validates :tag, presence: true

  def send_mail(user)
  	FeedbackMailer.send_mail_to_user(user).deliver
  end

  def send_reply(user, content)
    FeedbackMailer.send_reply_to_user(user, content).deliver
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :feedbacks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :feedbacks
  has_many :votes
  has_many :downvotes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :feedback
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController

	before_filter :authenticate_user!

	def create
		@feedback = Feedback.find(params[:feedback_id])
		@downvote = @feedback.downvotes.new do |downvote|
			downvote.user = current_user
		end
		
		if(vote = current_user.votes.find_by_feedback_id @feedback.id)
            vote.destroy!
        end

        @downvote.save!

        @feedback.update_attribute(:votes_count, get_votes_count)

		respond_to do |format|
			format.js
		end
		
	end

	def destroy
		@feedback = Feedback.find(params[:feedback_id])
		downvote = Downvote.find(params[:id])
		downvote.destroy

		@feedback.update_attribute(:votes_count, get_votes_count)

		respond_to do |format|
			format.js
		end
	end

	def get_votes_count
		votes_count = @feedback.votes.count - @feedback.downvotes.count
	end

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

	before_filter :auth_user!, except: [:show]
	before_filter :collect_data, only: [:new]
	before_filter :check_admin, only: [:reply_to_user, :reply]

	def new
		@feedback = Feedback.new
	end

	def create
		@feedback = Feedback.new feedback_parameters
		@feedback.user = current_user
		
		respond_to do |format|
			format.js
		end
	end

	def show
		@feedback = Feedback.find(params[:id])
		
	end

	def edit
		
	end

	def update
		
	end

	def destroy
		@feedback = Feedback.find(params[:id])
		@feedback.destroy
		redirect_to root_url
	end

	def reply
		@feedback = Feedback.find(params[:feedback_id])
	end

	def reply_to_user
		@feedback = Feedback.find(params[:feedback_id])
		@user = @feedback.user
		@feedback.update_attribute(:replied, true)
		@feedback.send_reply(@user, params[:reply_content])
		redirect_to root_url
	end

	def auth_user!(opts = {})
  		if admin_signed_in?
   			authenticate_admin!
  		else
    		authenticate_user!
  		end
	end

	def check_admin
		admin_signed_in?
	end

	private

		def collect_data
			@categories = Category.all
	  		@tags = Tag.all
		end

		def feedback_parameters
			params.require(:feedback).permit(:heading,:feedback_content, :when, :where, :category_id, :tag_id, :image)
		end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
  		@feedbacks = Feedback.paginate(page: params[:page], per_page: params[:per_page] || 15).order('votes_count DESC')
  		@categories = Category.all
  end

  def sort
  	@category = params[:static_pages][:category]
  	@categories = Category.all
  	@feedbacks = Feedback.where(category_id: @category).paginate(page: params[:page], per_page: params[:per_page] || 15).order('votes_count DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!

	def index
		@feedbacks = Feedback.where(user_id: current_user.id).paginate(page: params[:page], per_page: params[:per_page] || 15).order('created_at DESC')
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	before_filter :authenticate_user!

	def create
		@feedback = Feedback.find(params[:feedback_id])
		@vote = @feedback.votes.new do |vote|
			vote.user = current_user
		end
		
		if(downvote = current_user.downvotes.find_by_feedback_id @feedback.id)
            downvote.destroy!
        end

        @vote.save!

        @feedback.update_attribute(:votes_count, get_votes_count)

		respond_to do |format|
			format.js
		end
	end

	def destroy
		@feedback = Feedback.find(params[:feedback_id])
		vote = Vote.find(params[:id])
		vote.destroy

		@feedback.update_attribute(:votes_count, get_votes_count)

		respond_to do |format|
			format.js
		end
	end

	def get_votes_count
		votes_count = @feedback.votes.count - @feedback.downvotes.count
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
	
	def user_has_downvoted?(id)
		downvote = current_user.downvotes.find_by_feedback_id(id) 
	end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper

	def user_has_voted?(id)
		vote = current_user.votes.find_by_feedback_id(id) 
	end

end

app/views/downvotes/_delete_downvotes.html.erb
<%= form_for([downvote.feedback, downvote], method: :delete, remote: true) do |f| %>
	<%= f.button "<span class='glyphicon glyphicon-chevron-down'></span>".html_safe, class: 'downvote' %>
<% end %>

app/views/downvotes/_downvotes.html.erb
<%= form_for ([f, f.downvotes.build]), remote: true do |f| %>
	<%= f.button "<span class='glyphicon glyphicon-chevron-down'></span>".html_safe, class: 'upvote' %>
<% end %>

app/views/downvotes/create.js.erb
$("#vote-downvote-<%= @feedback.id %>").html("<%= escape_javascript render('static_pages/vote_downvote', f: @feedback) %>");
$("#vote-count-feedback-<%= @feedback.id %>").html("<%= @feedback.votes_count %>");

app/views/downvotes/destroy.js.erb
$("#vote-downvote-<%= @feedback.id %>").html("<%= escape_javascript render('static_pages/vote_downvote', f: @feedback) %>");
$("#vote-count-feedback-<%= @feedback.id %>").html("<%= (@feedback.votes.count - @feedback.downvotes.count) %>");

app/views/feedbacks/_form.html.erb
<div class="container">
      <br>
      <div class="row">
          <div class="col-lg-6" style="float:none !important; margin:0 auto;">
            <div class="well">
              <%= form_for(@feedback, html: { :multipart => true, class: "bs-example form-horizontal"}, remote: true)  do |f| %>
                <fieldset>
                  <legend>Submit Feedback</legend>
                  	
        					<div class="form-group">
        						<%= f.label :heading, class: "col-lg-2 control-label" %>
        						<div class="col-lg-10">
        							<%= f.text_field :heading, class: 'form-control' %>
        						</div>
        					</div>
                  	<div class="form-group">
                    	<%= f.label :feedback_content, class: "col-lg-2 control-label" %>
						          <div class="col-lg-10">
							         <%= f.text_area :feedback_content, rows: "5",  class: 'form-control', style: "height: 200px;" %>
						          </div>
                  	</div>

                  <div class="form-group">
                    <%= f.label :when, class: "col-lg-2 control-label" %>
                    <div class="col-lg-10">
						          <%= f.text_field :when, class: 'form-control' , id:"feedback-date" %>
					           </div>
                  </div>
                  
                  <div class="form-group">
                    <label class="col-lg-2 control-label">Type:</label>
                    <div class="col-lg-10">
                      <select id="select" name="feedback[tag_id]" class="form-control">
                      <% @tags.each do |tag| %>
                      	<option value="<%= tag.id %>"><%= tag.name %></option>
                      <% end %>
                    </select>
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="col-lg-2 control-label" for="select">Category:</label>
                    <div class="col-lg-10">
                      <select id="select" name="feedback[category_id]" class="form-control">
                      <% @categories.each do |category| %>
                      	<option value="<%= category.id %>"><%= category.name %></option>
                      <% end %>
                    </select>
                      
                    </div>
                  </div>

                  <div class="form-group">
                    <%= f.label :where, class: "col-lg-2 control-label" %>
					           <div class="col-lg-10">
						            <%= f.text_field :where, :id => 'gmaps-input-address', :placeholder => 'Start typing a place...', class: "form-control" %>
                    </div>
                  </div>
                  <div class="form-group">
                  	<%= f.label :image, class: "col-lg-2 control-label" %>
                  	<div class="col-lg-10">
				  		        <%= f.file_field :image, class: "form-control" %>
				  	         </div>
				          </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Submit</button> 
                      <button class="btn btn-default">Cancel</button> 
                    </div>
                  </div>
                </fieldset>
              <% end %>
            </div>
          </div>
        </div>
        <div id="error"></div>
</div>

app/views/feedbacks/create.js.erb
<% if remotipart_submitted? %>
	<% if @feedback.save %>
		<% @feedback.send_mail(@feedback.user) %>
		window.location.href = '<%= root_url %>'
	<% else %>
		$("#error").html("<div class='alert fade in alert-danger'><%= @feedback.errors.full_messages.first %>"+
      		"<button class='close' data-dismiss='alert'>×</button></div>");	
	<% end %>
<% else %>
	$("#error").html("<div class='alert fade in alert-danger'>Please upload some image"+
      		"<button class='close' data-dismiss='alert'>×</button></div>");	
<% end %>

app/views/feedbacks/new.html.erb
<%= render 'form' %>

app/views/feedbacks/reply.html.erb
<div class="row">
    <div class="col-lg-6" style="float:none !important; margin:0 auto;">
        <div class="well">
		<%= form_tag reply_to_user_path,  html: { class: "bs-example form-horizontal"},method: :post do %>
			<%= hidden_field_tag :feedback_id, @feedback.id %>
			<div class="form-group">
				<%= label_tag "feedback_reply" %>
				
					<%= text_area_tag :reply_content, "", rows: "5", class: 'form-control', style: 'height: 200px;' %>
				
            </div>
				
			<%= submit_tag "Reply", class: 'btn btn-default' %>
		<% end %>
		</div>
	</div>
</div>

app/views/feedbacks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8" style=" float: none !important; margin:0 auto;">
      <div class="well">
        <legend> Feedback </legend>
        <h4> 
          <%= @feedback.heading %>
          <span class="label label-success" style="float:right;"><%= @feedback.category.name unless @feedback.category.nil? %></span>
        </h4>
        <div id="category">
          <%= @feedback.tag.name unless @feedback.tag.nil? %>
        </div>
        <div style="margin-top: 10px;">
          <a href=""><i class="fa fa-calendar"></i></a>&nbsp;<%= @feedback.when.to_formatted_s(:long) %>
        </div>
        <div style="margin-top: 10px;">
          <a href=""><i class="fa fa-map-marker"></i></a>&nbsp;&nbsp;&nbsp;<%= @feedback.where %>
        </div>
        <h4>Feedback Content </h4>
        <div>
          <%= image_tag @feedback.image_url(:thumb) unless @feedback.image_url.nil? %>
        </div>
        <br>
        <div id="feedback-text">
          <p style="line-height: 3rem;"><%= @feedback.feedback_content %></p>
        </div>
        
        <br>
        <div id="social-share">
          <ul class="list-unstyled list-inline list-social-icons" style="text-align:right;">
            <li class="tooltip-social facebook-link">
              <a href="#facebook-profile" data-toggle="tooltip" data-placement="top" title="Facebook"><i    class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
              <a href="#linkedin-profile" data-toggle="tooltip" data-placement="top" title="LinkedIn"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
              <a href="#twitter-profile" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
          </ul>
        </div>
      </div> <!-- End well. -->
    </div> <!-- End Column. -->
  </div><!-- End Row. -->
</div> <!-- End container -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "FeedbackIt", root_url, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Create", new_feedback_path  %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Profile", profile_path %></li>
          <li><%= link_to "Signout", destroy_user_session_path, method: :delete %></li>
        <% elsif admin_signed_in? %>
          <li><%= link_to "Signout", destroy_admin_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FeedbackIt" %></title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <%= javascript_include_tag "application" %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/_feedback.html.erb
<div class="col-lg-8">
	<% @feedbacks.each do |f| %>
		<div id="feedback_<%= f.id %>" class="col-lg-12">
			<div id="votes" style="width:24px; float:left; margin-top:30px; height:auto;">
				<div id="vote-downvote-<%= f.id %>">
					<%= render 'static_pages/vote_downvote', f:f %>
				</div>
         	</div>
         	<div class="col-lg-10 col-small-12">
         		<div id="content" style="float:left; padding:1%;">
	         	<h2><%= link_to f.heading, feedback_url(f) %></h2>
				<p><%= f.feedback_content %></p>
				<% if admin_signed_in? %>
					<p><%= link_to "Reply", reply_url(f), class: 'btn btn-default' %>
					<%= link_to "Delete", feedback_url(f), method: :delete, class: 'btn btn-default' %></p>
				<% end %>
				<br>
            	<% if f.replied? %>
            		<span class="label label-success"><%= "Addressed" %></span>
            	<% else %>
            		<span class="label label-warning"><%= "Pending" %></span>
            	<% end %>
            	<span class="label label-success"><%= f.tag.name %></span>
          	</div>
          	</div>
		</div>
		<hr>
	<% end %>
	<%= will_paginate @feedbacks %>
</div>

app/views/static_pages/_vote_downvote.html.erb
<% if user_signed_in? %>
	<% if (vote = user_has_voted? f.id) %>
		<%= render 'votes/delete_votes', vote: vote %>
	<% else %>
		<%= render 'votes/votes', f:f %>
	<% end %>

	<div id="vote-count-feedback-<%= f.id %>" class="text-center">
		<%= f.votes.count - f.downvotes.count %>
	</div>

	<% if (downvote = user_has_downvoted? f.id) %>
		<%= render 'downvotes/delete_downvotes', downvote: downvote %>
	<% else %>
		<%= render 'downvotes/downvotes', f:f %>
	<% end %>
<% else %>
	<div id="vote-count-feedback-<%= f.id %>" class="text-center">
		<%= f.votes_count %>
	</div>	
<% end %>

app/views/static_pages/index.html.erb
<div class="row">
	<div class="col-lg-8">
		<% @feedbacks.each do |f| %>
			<div id="feedback_<%= f.id %>" class="col-lg-12">
				<div id="votes" style="width:24px; float:left; margin-top:30px; height:auto;">
					<div id="vote-downvote-<%= f.id %>">
						<%= render 'vote_downvote', f:f %>
					</div>
	         	</div>
	         	<div class="col-lg-10 col-small-12">
	         		<div id="content" style="float:left; padding:1%;">
		         	<h2><%= link_to f.heading, feedback_url(f) %></h2>
					<p><%= f.feedback_content %></p>
					<br>
	            	<span class="label label-success" style="float:right;"><%= f.tag.name %></span>
	          	</div>
	          	</div>
			</div>
			<hr>
		<% end %>
		<%= will_paginate @feedbacks %>
	</div>
	<div class="col-lg-4">
  		<div class="well">
    		<h4>Feedback By Category</h4>
  		</div><!-- /well -->
	</div><!-- End of col-4 -->		
</div>
	

app/views/static_pages/sort.html.erb
<div class="row">
	<%= render 'feedback' %>
	<div class="col-lg-4">
  		<div class="well">
    		<h4>Feedback By Category</h4>
    		<%= form_tag sort_url, method: :get do %>
      			<select name="static_pages[category]" id="select" class="form-control">
      				<% @categories.each do |category| %>
              			<% if category.id.to_s == @category.to_s %>
              				<option value="<%= category.id %>" selected><%= category.name %></option>
              			<% else %>
              				<option value="<%= category.id %>"><%= category.name %></option>
              			<% end %>
              		<% end %>
            	</select>
            	<br>
      			<%= submit_tag :search, class: "btn btn-default" %>
      		<% end %>
  		</div><!-- /well -->
	</div><!-- End of col-4 -->		
</div>
	

app/views/users/index.html.erb
<div class="row">
	Hello <%= current_user.name %><br />
	<h2> Your Feedbacks </h2>
	<div><%= render 'static_pages/feedback' %></div>
</div>

app/views/votes/_delete_votes.html.erb
<%= form_for([vote.feedback, vote], method: :delete, remote: true) do |f| %>
	<%= f.button "<span class='glyphicon glyphicon-chevron-up'></span>".html_safe, class: 'downvote' %>
<% end %>

app/views/votes/_votes.html.erb
<%= form_for ([f, f.votes.build]), remote: true do |f| %>
	<%= f.button "<span class='glyphicon glyphicon-chevron-up'></span>".html_safe, class: 'upvote' %>
<% end %>

app/views/votes/create.js.erb
$("#vote-downvote-<%= @feedback.id %>").html("<%= escape_javascript render('static_pages/vote_downvote', f: @feedback) %>");
$("#vote-count-feedback-<%= @feedback.id %>").html("<%= @feedback.votes_count %>");

app/views/votes/destroy.js.erb
$("#vote-downvote-<%= @feedback.id %>").html("<%= escape_javascript render('static_pages/vote_downvote', f: @feedback) %>");
$("#vote-count-feedback-<%= @feedback.id %>").html("<%= (@feedback.votes_count) %>");